module_Jobs: true
module_Factions: true
module_Market: true
module_Leaderboard: true
disabledCommands: []
module_Chat: true
module_Homes: true
module_Leveling: true
module_Titles: true
module_Relics: true
module_Events: true
module_Utils: true
module_Ranks: true
joinMessage: true
module_Dimensions: true
disabledDimensions: []
forceDisableBroadcasts: false
bannedWords: []