name: GrimmsServer
main: org.gsdistance.grimmsServer.GrimmsServer
version: ${version}
api-version: 1.16
commands:
  logselfstats:
    description: Displays the player's own stats including death count, money, and total kills.
    usage: /logselfstats
