name: GrimmsServer
main: org.gsdistance.grimmsServer.GrimmsServer
version: ${version}
api-version: 1.16
commands:
  logSelfStats:
    description: Displays the player's own stats including death count, money, and total kills.
    usage: /logSelfStats
    permission: grimmsserver.logSelfStats
  logWorldStats:
    description: Displays the world stats including total deaths, total kills, and total money.
    usage: /logWorldStats
    permission: grimmsserver.logWorldStats
  sellItem:
    description: Sells the main hand for a certain amount of money.
    usage: /sellItem
    permission: grimmsserver.sellItem
  buyItem:
    description: Buys an item for a certain amount of money.
    usage: /buyItem <item> <amount>
    permission: grimmsserver.buyItem
  getMarketStock:
    description: Displays the market stock of a specified item.
    usage: /getMarketStock <item>
    permission: grimmsserver.getMarketStock
  getMarket:
    description: Dumps the whole market information.
    usage: /getMarket
    permission: grimmsserver.getMarket
  logLeaderboard:
    description: Displays the leaderboard of players with the most kills.
    usage: /logLeaderboard
    permission: grimmsserver.logLeaderboard
  sendMoney:
    description: Sends money to another player.
    usage: /sendMoney <player> <amount>
    permission: grimmsserver.sendMoney
  buyRipoff:
    description: Buys the item for 10x base price, but can be bought when not available.
    usage: /buyRipoff <item> <amount>
    permission: grimmsserver.buyRipoff
  makeItemLevelable:
    description: Makes the main hand item levelable for 3500 money.
    usage: /makeItemLevelable
    permission: grimmsserver.makeItemLevelable
  setPlayerStat:
    description: Set a player's stats.
    usage: /setPlayerStat <player> <statId> <value>
    permission: grimmsserver.setPlayerStat
  logPlayerStats:
    description: Displays the stats of a specified player.
    usage: /logPlayerStats <player>
    permission: grimmsserver.logPlayerStats
  logSelfTitles:
    description: Displays the titles of the player.
    usage: /logSelfTitles
    permission: grimmsserver.logSelfTitles
  logPlayerTitles:
    description: Displays the titles of a specified player.
    usage: /logPlayerTitles <player>
    permission: grimmsserver.logPlayerTitles
  addTitle:
    description: Adds a title to a player.
    usage: /addTitle <player> <title>
    permission: grimmsserver.addTitle
  executePlayer:
    description: Executes a player, requires title Executioner.
    usage: /executePlayer <player>
    permission: grimmsserver.executePlayer
  buyEnchantment:
    description: Buys 1 level of <enchant> for money
    usage: /buyEnchantment <enchantId>
    permission: grimmsserver.buyEnchantment
  logEnchantmentCosts:
    description: Displays the costs of all available
    usage: /logEnchantmentCosts
    permission: grimmsserver.logEnchantmentCosts
  logJobs:
    description: Displays all available jobs
    usage: /logJobs
    permission: grimmsserver.logJobs
  takeJob:
    description: Take a job if you meet it's requirements
    usage: /takeJob <jobId>
    permission: grimmsserver.takeJob
  grimmsServerCommands:
    description: Displays all existing GrimmsServer commands
    usage: /grimmsServerCommands
permissions:
  grimmsserver.logSelfStats:
    description: Allows a player to log their own stats
    default: true
  grimmsserver.logWorldStats:
    description: Allows a player to log world stats
    default: true
  grimmsserver.sellItem:
    description: Allows a player to sell an item
    default: true
  grimmsserver.buyItem:
    description: Allows a player to buy an item
    default: true
  grimmsserver.getMarketStock:
    description: Allows a player to get market stock
    default: true
  grimmsserver.getMarket:
    description: Allows a player to get market information
    default: true
  grimmsserver.logLeaderboard:
    description: Allows a player to log the leaderboard
    default: true
  grimmsserver.sendMoney:
    description: Allows a player to send money to another player
    default: true
  grimmsserver.buyRipoff:
    description: Allows a player to buy an item at a higher price
    default: true
  grimmsserver.makeItemLevelable:
    description: Allows a player to make an item levelable
    default: true
  grimmsserver.setPlayerStat:
    description: Allows a player to set another player's stats
    default: op
  grimmsserver.logPlayerStats:
    description: Allows a player to log another player's stats
    default: op
  grimmsserver.logSelfTitles:
    description: Allows a player to log their own titles
    default: true
  grimmsserver.logPlayerTitles:
    description: Allows a player to log another player's titles
    default: true
  grimmsserver.addTitle:
    description: Allows a player to add a title to another player
    default: op
  grimmsserver.executePlayer:
    description: Allows a player to execute another player
    default: true
  grimmsserver.buyEnchantment:
    description: Allows a player to buy an enchantment
    default: true
  grimmsserver.logEnchantmentCosts:
    description: Allows a player to log enchantment costs
    default: true
  grimmsserver.multiHome:
    description: Allows multiple homes to be set
    default: op
  grimmsserver.logJobs:
    description: Allows a player to log available jobs
    default: true
  grimmsserver.takeJob:
    description: Allows a player to acquire a job title
    default: true